source 'https://rubygems.org'

gem 'rails', '4.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'mysql2'
gem 'resque'

gem 'activeadmin',					github: 'gregbell/active_admin',	branch: 'rails4'
# gem 'ransack',							github: 'ernie/ransack',					branch: 'rails-4'
gem 'inherited_resources',	github: 'josevalim/inherited_resources'
gem 'protected_attributes' #necessary for AA, remove later!

# HTML parsing
# gem 'nokogiri'
# gem 'httparty'
gem 'openlibrary', 					github: 'kcorbitt/openlibrary', 	branch: 'rails4'

# Queue
gem 'resque', require: 'resque/server'

# Assets
gem 'bourbon'
gem 'coffee-rails'
gem 'sass-rails'

# Javascript compression
gem 'uglifier', '>= 1.0.3'

gem 'turbolinks'
gem 'jbuilder'

# templating
gem 'slim'
gem 'redcarpet'

# Front end
gem 'jquery-rails'
gem 'bootstrap-sass'

group :development do 
	gem 'capistrano', require: false
	gem 'capistrano-ext', require: false
	gem 'capistrano-unicorn', require: false
	gem 'capistrano-remote-cache-with-project-root'#, require: false
	gem 'capistrano-resque', require: false
	gem 'cape', require: false
end

group :production do 
	gem 'unicorn'
end