source 'https://rubygems.org'

gem 'rails', '4.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'mysql2'

gem 'activeadmin',					github: 'gregbell/active_admin',	branch: 'rails4'
gem 'ransack',							github: 'ernie/ransack',					branch: 'rails-4'
gem 'inherited_resources',	github: 'josevalim/inherited_resources'
gem 'protected_attributes' #necessary for AA, remove later!

# HTML parsing
# gem 'nokogiri'
# gem 'httparty'
gem 'openlibrary', 					github: 'kcorbitt/openlibrary', 	branch: 'rails4'

# Queue
gem 'resque', require: 'resque/server'

# Assets
gem 'bourbon'
gem 'coffee-rails', '~> 4.0.0'
gem 'sass-rails', '~> 4.0.0'

# Javascript compression
gem 'uglifier', '>= 1.0.3'

gem 'turbolinks'
gem 'jbuilder'

# templating
gem 'slim'
gem 'redcarpet'

# Front end
gem 'jquery-rails'
gem 'bootstrap-sass'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano', group: :development

# To use debugger
# gem 'debugger'
